### ISSUE TITLE
Share some dev insights

### ISSUE THREAD

**Issue by KNGP14** [michalleptuch/desktop-toolkit#5]
Would you share some development insights?
I would really like to create those "taskbar flyout apps" with minimal gui too.

But it's a little bit challenging to create this modern style, without borders, centered above the systray icon and backward compatibility to windows 10..
Just some hints would be really great :-)

**Comment by michalleptuch** [comment]
Hi Kevin,
look at my another repo: https://github.com/michalleptuch/rounded-flyout. It's archived and not supported anymore, but I hope it may help you. 🙂

**Comment by KNGP14** [comment]
Ahh.. Really cool - thank u 😊
